In [1]:
from collections import defaultdict
from scipy import stats
from scipy.stats import erlang, expon, norm 
from itertools import product, combinations
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
import time # benchmarking

# User Defined Modules
import Graph

# Debugging runtime edge case where sometimes parents will establish a cycle
- this mutal setting isn't consistent
- have an easier time forcing it on ER

In [2]:
data = Graph.erdos_renyi_simulation_trial(5, 1, '0', '3', iters=10)

defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d63480>, {'0': None, '1': '4', '2': None, '4': '0', '3': '4'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d954e0>, {'0': None, '1': '4', '2': '0', '4': '2', '3': '1'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d63530>, {'0': None, '1': None, '2': None, '4': None, '3': '0'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d956f0>, {'0': None, '1': None, '2': '0', '4': None, '3': '0'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d63320>, {'0': None, '1': None, '2': None, '4': None, '3': '0'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d957a0>, {'0': None, '1': None, '2': '4', '4': '0', '3': '2'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d63530>, {'0': None, '1': None, '2': '0', '4': None, '3': '0'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d95430>, {'0': None, '1': None, '2': None, '4': '0', '3': '0'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d633d0>, {'0': None, '1': '0', '2': '1', '4': '1', '3': '0'})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fe6d1d95640>, {'0': None, '1': None, '2': '0', '4': None, '3': '0'})

In [3]:
data

(defaultdict(<function Graph.erdos_renyi_simulation_trial.<locals>.<lambda>()>,
             {('3', '4', '0'): 1,
              ('3', '1', '4', '2', '0'): 1,
              ('3', '0'): 7,
              ('3', '2', '4', '0'): 1}),
 defaultdict(list,
             {('3', '4', '0'): [np.float64(0.3702243159546842)],
              ('3', '1', '4', '2', '0'): [np.float64(0.7457305618401497)],
              ('3', '0'): [np.float64(0.1572103302379076),
               np.float64(2.578773943152844),
               np.float64(0.08247423757272336),
               np.float64(0.29992120105828585),
               np.float64(0.2343675770873209),
               np.float64(0.3821325880662025),
               np.float64(0.5003840285160537)],
              ('3', '2', '4', '0'): [np.float64(0.21507157773862992)]}))

# Contrived Example, odd printing?

In [16]:
exp_t = lambda t: 1 - np.e**(-t)

edge_set = {
    "1,2": { "distribution": "E", "parameters": { "lambda" : 1.0 }}, 
    "2,3": { "distribution": "E", "parameters": { "lambda" : 1.0 }}, 
    "3,1": { "distribution": "E", "parameters": { "lambda" : 1.0 }}, 
}

g = Graph.Graph(edge_set)

In [17]:
display(g._adjency_matrix)

           1          2          3
0
1        inf  <scipy...  <scipy...
2  <scipy...        inf  <scipy...
3  <scipy...  <scipy...        inf

In [10]:
t = g.simulate_gossip_rv('1','3', log=False)
path = g.construct_path('3')

In [11]:
help(display)

Help on function display in module IPython.core.display_functions:

display(
    *objs,
    include=None,
    exclude=None,
    metadata=None,
    transient=None,
    display_id=None,
    raw=False,
    clear=False,
    **kwargs
)
    Display a Python object in all frontends.

    By default all representations will be computed and sent to the frontends.
    Frontends can decide which representation is used and how.

    In terminal IPython this will be similar to using :func:`print`, for use in richer
    frontends see Jupyter notebook examples with rich display logic.

    Parameters
    ----------
    *objs : object
        The Python objects to display.
    raw : bool, optional
        Are the objects to be displayed already mimetype-keyed dicts of raw display data,
        or Python objects that need to be formatted before display? [default: False]
    include : list, tuple or set, optional
        A list of format type strings (MIME types) to include in the
        format data dict. If this is set *only* the format types included
        in this list will be computed.
    exclude : list, tuple or set, optional
        A list of format type strings (MIME types) to exclude in the format
        data dict. If this is set all format types will be computed,
        except for those included in this argument.
    metadata : dict, optional
        A dictionary of metadata to associate with the output.
        mime-type keys in this dictionary will be associated with the individual
        representation formats, if they exist.
    transient : dict, optional
        A dictionary of transient data to associate with the output.
        Data in this dict should not be persisted to files (e.g. notebooks).
    display_id : str, bool optional
        Set an id for the display.
        This id can be used for updating this display area later via update_display.
        If given as `True`, generate a new `display_id`
    clear : bool, optional
        Should the output area be cleared before displaying anything? If True,
        this will wait for additional output before clearing. [default: False]
    **kwargs : additional keyword-args, optional
        Additional keyword-arguments are passed through to the display publisher.

    Returns
    -------
    handle: DisplayHandle
        Returns a handle on updatable displays for use with :func:`update_display`,
        if `display_id` is given. Returns :py:data:`None` if no `display_id` is given
        (default).

    Examples
    --------
    >>> class Json(object):
    ...     def __init__(self, json):
    ...         self.json = json
    ...     def _repr_pretty_(self, pp, cycle):
    ...         import json
    ...         pp.text(json.dumps(self.json, indent=2))
    ...     def __repr__(self):
    ...         return str(self.json)
    ...

    >>> d = Json({1:2, 3: {4:5}})

    >>> print(d)
    {1: 2, 3: {4: 5}}

    >>> display(d)
    {
      "1": 2,
      "3": {
        "4": 5
      }
    }

    >>> def int_formatter(integer, pp, cycle):
    ...     pp.text('I'*integer)

    >>> plain = get_ipython().display_formatter.formatters['text/plain']
    >>> plain.for_type(int, int_formatter)
    <function _repr_pprint at 0x...>
    >>> display(7-5)
    II

    >>> del plain.type_printers[int]
    >>> display(7-5)
    2

    See Also
    --------
    :func:`update_display`

    Notes
    -----
    In Python, objects can declare their textual representation using the
    `__repr__` method. IPython expands on this idea and allows objects to declare
    other, rich representations including:

      - HTML
      - JSON
      - PNG
      - JPEG
      - SVG
      - LaTeX

    A single object can declare some or all of these representations; all are
    handled by IPython's display system.

    The main idea of the first approach is that you have to implement special
    display methods when you define your class, one for each representation you
    want to use. Here is a list of the names of the special methods and the
    values they must return:

      - `_repr_html_`: return raw HTML as a string, or a tuple (see below).
      - `_repr_json_`: return a JSONable dict, or a tuple (see below).
      - `_repr_jpeg_`: return raw JPEG data, or a tuple (see below).
      - `_repr_png_`: return raw PNG data, or a tuple (see below).
      - `_repr_svg_`: return raw SVG data as a string, or a tuple (see below).
      - `_repr_latex_`: return LaTeX commands in a string surrounded by "$",
                        or a tuple (see below).
      - `_repr_mimebundle_`: return a full mimebundle containing the mapping
                             from all mimetypes to data.
                             Use this for any mime-type not listed above.

    The above functions may also return the object's metadata alonside the
    data.  If the metadata is available, the functions will return a tuple
    containing the data and metadata, in that order.  If there is no metadata
    available, then the functions will return the data only.

    When you are directly writing your own classes, you can adapt them for
    display in IPython by following the above approach. But in practice, you
    often need to work with existing classes that you can't easily modify.

    You can refer to the documentation on integrating with the display system in
    order to register custom formatters for already existing types
    (:ref:`integrating_rich_display`).

    .. versionadded:: 5.4 display available without import
    .. versionadded:: 6.1 display available without import

    Since IPython 5.4 and 6.1 :func:`display` is automatically made available to
    the user without import. If you are using display in a document that might
    be used in a pure python context or with older version of IPython, use the
    following import at the top of your file::

        from IPython.display import display

In [8]:
g.reset_simulation()
display(g._adjency_matrix)

           1          2          3
0
1        inf  <scipy...  <scipy...
2  <scipy...        inf  <scipy...
3  <scipy...  <scipy...        inf