In [25]:
from infection_propagation import Graph
from infection_propagation import Figures
import importlib
importlib.reload(Graph)
importlib.reload(Figures)

In [26]:
threshold_value = lambda x : np.log(x)/x
n = 5
p = 1.2*threshold_value(n)
h = Graph.erdos_renyi(n, p, force_connection=True)
print(f"Threshold value: {threshold_value(n)}")
print(f"P value: {p}")

Threshold value: 0.32188758248682003
P value: 0.38626509898418404

In [27]:
h._adjency_matrix

           2          3          4          0          1
0
0  <tree_...  <tree_...  <tree_...        inf        inf
1        inf  <tree_...  <tree_...        inf        inf
2        inf  <tree_...  <tree_...  <tree_...        inf
3  <tree_...        inf        inf  <tree_...  <tree_...
4  <tree_...        inf        inf  <tree_...  <tree_...

In [28]:
t = h.simulate_gossip_rv('1', '4')
print(t)

1.194624541708707

In [29]:
h._adjency_matrix

         2        3         4    0         1
0
0      inf      inf       inf  inf       inf
1      inf      inf  0.798806  inf       inf
2      inf -0.51428   0.48222  inf       inf
3 -0.51428      inf       inf  inf       inf
4  0.48222      inf       inf  inf  0.798806

In [30]:
h.sim_all(reset=True)

In [31]:
h._adjency_matrix

          2         3         4         0         1
0
0  0.057897  0.682554  0.112175       inf       inf
1       inf  0.342334  1.334631       inf       inf
2       inf  0.107321  0.037465  0.057897       inf
3  0.107321       inf       inf  0.682554  0.342334
4  0.037465       inf       inf  0.112175  1.334631

In [32]:
t = h.algo_jump('1', '4', algorithm="")
print(t)

0.48711987528042994

In [33]:
h.construct_path('1', '4')

['4', '2', '3', '1']

In [34]:
t = h.algo_jump('1', '4', algorithm="bidir")
print(t)

defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '1', '0': '2', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '1', '0': '2', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '2', '0': '2', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '0', '0': '2', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '1', '0': '2', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '1', '0': '2', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '1', '0': '3', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '0', '4': '1', '0': '3', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '1', '0': '3', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '2', '0': '3', '3': '1', '1': None})
defaultdict(<function Graph.__init__.<locals>.<lambda> at 0x7fd39b7e24b0>, {'2': '3', '4': '2', '0': '2', '3': '1', '1': None})
0.48711987528042994

In [35]:
h.construct_path('1','4')

['4', '2', '3', '1']

# Not Full Implemented, sometimes returns incorrect path